DELETE FROM component_parts;
DELETE FROM tech_reviews;
DELETE FROM products;
DELETE FROM product_type_parts;
DELETE FROM product_types;

INSERT INTO product_types (id, name, created_at) VALUES
('Wardrobe', 'Wardrobe', NOW()),
('Wardrobe Big', 'Wardrobe Big', NOW()),
('Cabinet', 'Cabinet', NOW()),
('Cabinet Small', 'Cabinet Small', NOW()),
('High Cabinet', 'High Cabinet', NOW()),
('Drawer Cabinet', 'Drawer Cabinet', NOW()),
('Backwall', 'Backwall', NOW()),
('Lightbox', 'Lightbox', NOW()),
('Island', 'Island', NOW()),
('Reception Desk', 'Reception Desk', NOW()),
('Display Podium', 'Display Podium', NOW()),
('Display Counter', 'Display Counter', NOW()),
('Display Unit', 'Display Unit', NOW()),
('Sideboard', 'Sideboard', NOW()),
('Storage Unit', 'Storage Unit', NOW()),
('Bar', 'Bar', NOW()),
('Table', 'Table', NOW()),
('Bench', 'Bench', NOW()),
('Pouf', 'Pouf', NOW()),
('Mirror', 'Mirror', NOW()),
('Mirror Stand', 'Mirror Stand', NOW()),
('Canopy', 'Canopy', NOW()),
('Ceiling Panel', 'Ceiling Panel', NOW()),
('Kitchen', 'Kitchen', NOW()),
('Wall Panel', 'Wall Panel', NOW()),
('Partition Wall', 'Partition Wall', NOW()),
('Visual Large', 'Visual Large', NOW()),
('Visual Small', 'Visual Small', NOW()),
('Flooring', 'Flooring', NOW()),
('Lighting Fixture', 'Lighting Fixture', NOW()),
('Decor Frame', 'Decor Frame', NOW());

INSERT INTO product_type_parts (id, product_type_id, name, sort_order, created_at) VALUES
('PTP-Wardrobe-1', 'Wardrobe', 'Carcass', 1, NOW()),
('PTP-Wardrobe-2', 'Wardrobe', 'Sides', 2, NOW()),
('PTP-Wardrobe-3', 'Wardrobe', 'Back panel', 3, NOW()),
('PTP-Wardrobe-4', 'Wardrobe', 'Doors', 4, NOW()),
('PTP-Wardrobe-5', 'Wardrobe', 'Shelves', 5, NOW()),
('PTP-Wardrobe-6', 'Wardrobe', 'Drawers', 6, NOW()),
('PTP-Wardrobe-7', 'Wardrobe', 'Plinth', 7, NOW()),
('PTP-Wardrobe-8', 'Wardrobe', 'Top panel', 8, NOW()),
('PTP-Wardrobe-9', 'Wardrobe', 'Hanger rail', 9, NOW()),

('PTP-WardrobeBig-1', 'Wardrobe Big', 'Carcass', 1, NOW()),
('PTP-WardrobeBig-2', 'Wardrobe Big', 'Sides', 2, NOW()),
('PTP-WardrobeBig-3', 'Wardrobe Big', 'Back panel', 3, NOW()),
('PTP-WardrobeBig-4', 'Wardrobe Big', 'Double doors', 4, NOW()),
('PTP-WardrobeBig-5', 'Wardrobe Big', 'Shelves', 5, NOW()),
('PTP-WardrobeBig-6', 'Wardrobe Big', 'Drawers', 6, NOW()),
('PTP-WardrobeBig-7', 'Wardrobe Big', 'Plinth', 7, NOW()),
('PTP-WardrobeBig-8', 'Wardrobe Big', 'Top cover', 8, NOW()),
('PTP-WardrobeBig-9', 'Wardrobe Big', 'Lighting panel', 9, NOW()),

('PTP-Cabinet-1', 'Cabinet', 'Carcass', 1, NOW()),
('PTP-Cabinet-2', 'Cabinet', 'Sides', 2, NOW()),
('PTP-Cabinet-3', 'Cabinet', 'Back panel', 3, NOW()),
('PTP-Cabinet-4', 'Cabinet', 'Doors', 4, NOW()),
('PTP-Cabinet-5', 'Cabinet', 'Shelves', 5, NOW()),
('PTP-Cabinet-6', 'Cabinet', 'Top panel', 6, NOW()),
('PTP-Cabinet-7', 'Cabinet', 'Base', 7, NOW()),
('PTP-Cabinet-8', 'Cabinet', 'Plinth', 8, NOW()),

('PTP-CabinetSmall-1', 'Cabinet Small', 'Carcass', 1, NOW()),
('PTP-CabinetSmall-2', 'Cabinet Small', 'Doors', 2, NOW()),
('PTP-CabinetSmall-3', 'Cabinet Small', 'Shelf', 3, NOW()),
('PTP-CabinetSmall-4', 'Cabinet Small', 'Back panel', 4, NOW()),
('PTP-CabinetSmall-5', 'Cabinet Small', 'Plinth', 5, NOW()),
('PTP-CabinetSmall-6', 'Cabinet Small', 'Top cover', 6, NOW()),

('PTP-HighCabinet-1', 'High Cabinet', 'Carcass', 1, NOW()),
('PTP-HighCabinet-2', 'High Cabinet', 'Sides', 2, NOW()),
('PTP-HighCabinet-3', 'High Cabinet', 'Back panel', 3, NOW()),
('PTP-HighCabinet-4', 'High Cabinet', 'Doors', 4, NOW()),
('PTP-HighCabinet-5', 'High Cabinet', 'Shelves', 5, NOW()),
('PTP-HighCabinet-6', 'High Cabinet', 'Drawers', 6, NOW()),
('PTP-HighCabinet-7', 'High Cabinet', 'Top', 7, NOW()),
('PTP-HighCabinet-8', 'High Cabinet', 'Base', 8, NOW()),
('PTP-HighCabinet-9', 'High Cabinet', 'Plinth', 9, NOW()),

('PTP-DrawerCabinet-1', 'Drawer Cabinet', 'Carcass', 1, NOW()),
('PTP-DrawerCabinet-2', 'Drawer Cabinet', 'Drawer fronts', 2, NOW()),
('PTP-DrawerCabinet-3', 'Drawer Cabinet', 'Drawer boxes', 3, NOW()),
('PTP-DrawerCabinet-4', 'Drawer Cabinet', 'Top panel', 4, NOW()),
('PTP-DrawerCabinet-5', 'Drawer Cabinet', 'Plinth', 5, NOW()),
('PTP-DrawerCabinet-6', 'Drawer Cabinet', 'Handles', 6, NOW()),

('PTP-Backwall-1', 'Backwall', 'Front fascia', 1, NOW()),
('PTP-Backwall-2', 'Backwall', 'Back panel', 2, NOW()),
('PTP-Backwall-3', 'Backwall', 'Sides', 3, NOW()),
('PTP-Backwall-4', 'Backwall', 'Visual / Lightbox', 4, NOW()),
('PTP-Backwall-5', 'Backwall', 'Logo', 5, NOW()),
('PTP-Backwall-6', 'Backwall', 'Cabinet / Storage base', 6, NOW()),
('PTP-Backwall-7', 'Backwall', 'Shelves', 7, NOW()),
('PTP-Backwall-8', 'Backwall', 'Worktop / Countertop', 8, NOW()),
('PTP-Backwall-9', 'Backwall', 'Plinth', 9, NOW()),

('PTP-Lightbox-1', 'Lightbox', 'Frame', 1, NOW()),
('PTP-Lightbox-2', 'Lightbox', 'Back panel', 2, NOW()),
('PTP-Lightbox-3', 'Lightbox', 'LED diffusion layer', 3, NOW()),
('PTP-Lightbox-4', 'Lightbox', 'Printed visual', 4, NOW()),
('PTP-Lightbox-5', 'Lightbox', 'Electrical cover', 5, NOW()),

('PTP-Island-1', 'Island', 'Top / Countertop', 1, NOW()),
('PTP-Island-2', 'Island', 'Base cabinet', 2, NOW()),
('PTP-Island-3', 'Island', 'Sides', 3, NOW()),
('PTP-Island-4', 'Island', 'Back panel', 4, NOW()),
('PTP-Island-5', 'Island', 'Shelves', 5, NOW()),
('PTP-Island-6', 'Island', 'Drawers', 6, NOW()),
('PTP-Island-7', 'Island', 'Plinth', 7, NOW()),

('PTP-ReceptionDesk-1', 'Reception Desk', 'Countertop', 1, NOW()),
('PTP-ReceptionDesk-2', 'Reception Desk', 'Front panel', 2, NOW()),
('PTP-ReceptionDesk-3', 'Reception Desk', 'Side panels', 3, NOW()),
('PTP-ReceptionDesk-4', 'Reception Desk', 'Base frame', 4, NOW()),
('PTP-ReceptionDesk-5', 'Reception Desk', 'Inner shelves', 5, NOW()),
('PTP-ReceptionDesk-6', 'Reception Desk', 'Logo or branding panel', 6, NOW()),
('PTP-ReceptionDesk-7', 'Reception Desk', 'Plinth', 7, NOW()),

('PTP-DisplayPodium-1', 'Display Podium', 'Top panel', 1, NOW()),
('PTP-DisplayPodium-2', 'Display Podium', 'Carcass', 2, NOW()),
('PTP-DisplayPodium-3', 'Display Podium', 'Side cladding', 3, NOW()),
('PTP-DisplayPodium-4', 'Display Podium', 'Base frame', 4, NOW()),
('PTP-DisplayPodium-5', 'Display Podium', 'Logo plate', 5, NOW()),

('PTP-DisplayCounter-1', 'Display Counter', 'Top glass', 1, NOW()),
('PTP-DisplayCounter-2', 'Display Counter', 'Base cabinet', 2, NOW()),
('PTP-DisplayCounter-3', 'Display Counter', 'Front fascia', 3, NOW()),
('PTP-DisplayCounter-4', 'Display Counter', 'Lighting channel', 4, NOW()),
('PTP-DisplayCounter-5', 'Display Counter', 'Storage compartment', 5, NOW()),

('PTP-DisplayUnit-1', 'Display Unit', 'Carcass', 1, NOW()),
('PTP-DisplayUnit-2', 'Display Unit', 'Glass shelves', 2, NOW()),
('PTP-DisplayUnit-3', 'Display Unit', 'Glass sides', 3, NOW()),
('PTP-DisplayUnit-4', 'Display Unit', 'Lighting top', 4, NOW()),
('PTP-DisplayUnit-5', 'Display Unit', 'Logo area', 5, NOW()),
('PTP-DisplayUnit-6', 'Display Unit', 'Plinth', 6, NOW()),

('PTP-Sideboard-1', 'Sideboard', 'Top', 1, NOW()),
('PTP-Sideboard-2', 'Sideboard', 'Carcass', 2, NOW()),
('PTP-Sideboard-3', 'Sideboard', 'Doors', 3, NOW()),
('PTP-Sideboard-4', 'Sideboard', 'Drawers', 4, NOW()),
('PTP-Sideboard-5', 'Sideboard', 'Base frame', 5, NOW()),
('PTP-Sideboard-6', 'Sideboard', 'Back panel', 6, NOW()),

('PTP-StorageUnit-1', 'Storage Unit', 'Carcass', 1, NOW()),
('PTP-StorageUnit-2', 'Storage Unit', 'Shelves', 2, NOW()),
('PTP-StorageUnit-3', 'Storage Unit', 'Back panel', 3, NOW()),
('PTP-StorageUnit-4', 'Storage Unit', 'Doors', 4, NOW()),
('PTP-StorageUnit-5', 'Storage Unit', 'Drawers', 5, NOW()),
('PTP-StorageUnit-6', 'Storage Unit', 'Plinth', 6, NOW()),

('PTP-Bar-1', 'Bar', 'Worktop', 1, NOW()),
('PTP-Bar-2', 'Bar', 'Front panel', 2, NOW()),
('PTP-Bar-3', 'Bar', 'Base', 3, NOW()),
('PTP-Bar-4', 'Bar', 'Side panels', 4, NOW()),
('PTP-Bar-5', 'Bar', 'Shelves', 5, NOW()),
('PTP-Bar-6', 'Bar', 'Footrest', 6, NOW()),
('PTP-Bar-7', 'Bar', 'Lighting', 7, NOW()),

('PTP-Table-1', 'Table', 'Top panel', 1, NOW()),
('PTP-Table-2', 'Table', 'Legs / Frame', 2, NOW()),
('PTP-Table-3', 'Table', 'Support beams', 3, NOW()),
('PTP-Table-4', 'Table', 'Skirting / apron', 4, NOW()),

('PTP-Bench-1', 'Bench', 'Seat panel', 1, NOW()),
('PTP-Bench-2', 'Bench', 'Base frame', 2, NOW()),
('PTP-Bench-3', 'Bench', 'Legs', 3, NOW()),
('PTP-Bench-4', 'Bench', 'Backrest (optional)', 4, NOW()),
('PTP-Bench-5', 'Bench', 'Upholstery', 5, NOW()),

('PTP-Pouf-1', 'Pouf', 'Structure frame', 1, NOW()),
('PTP-Pouf-2', 'Pouf', 'Seat foam', 2, NOW()),
('PTP-Pouf-3', 'Pouf', 'Upholstery cover', 3, NOW()),
('PTP-Pouf-4', 'Pouf', 'Base support', 4, NOW()),

('PTP-Mirror-1', 'Mirror', 'Frame', 1, NOW()),
('PTP-Mirror-2', 'Mirror', 'Mirror glass', 2, NOW()),
('PTP-Mirror-3', 'Mirror', 'Back panel', 3, NOW()),
('PTP-Mirror-4', 'Mirror', 'Wall fixings', 4, NOW()),

('PTP-MirrorStand-1', 'Mirror Stand', 'Frame', 1, NOW()),
('PTP-MirrorStand-2', 'Mirror Stand', 'Mirror glass', 2, NOW()),
('PTP-MirrorStand-3', 'Mirror Stand', 'Base support', 3, NOW()),
('PTP-MirrorStand-4', 'Mirror Stand', 'Safety bracket', 4, NOW()),

('PTP-Canopy-1', 'Canopy', 'Main frame', 1, NOW()),
('PTP-Canopy-2', 'Canopy', 'Top panel', 2, NOW()),
('PTP-Canopy-3', 'Canopy', 'Side panels', 3, NOW()),
('PTP-Canopy-4', 'Canopy', 'Ceiling cladding', 4, NOW()),
('PTP-Canopy-5', 'Canopy', 'LED channel', 5, NOW()),

('PTP-CeilingPanel-1', 'Ceiling Panel', 'Frame', 1, NOW()),
('PTP-CeilingPanel-2', 'Ceiling Panel', 'Top cladding', 2, NOW()),
('PTP-CeilingPanel-3', 'Ceiling Panel', 'Acoustic panel', 3, NOW()),
('PTP-CeilingPanel-4', 'Ceiling Panel', 'Fixing brackets', 4, NOW()),

('PTP-Kitchen-1', 'Kitchen', 'Worktop', 1, NOW()),
('PTP-Kitchen-2', 'Kitchen', 'Upper cabinets', 2, NOW()),
('PTP-Kitchen-3', 'Kitchen', 'Lower cabinets', 3, NOW()),
('PTP-Kitchen-4', 'Kitchen', 'Backsplash', 4, NOW()),
('PTP-Kitchen-5', 'Kitchen', 'Plinth', 5, NOW()),
('PTP-Kitchen-6', 'Kitchen', 'Wall panels', 6, NOW()),
('PTP-Kitchen-7', 'Kitchen', 'Hinges / Handles', 7, NOW()),

('PTP-WallPanel-1', 'Wall Panel', 'Main panel', 1, NOW()),
('PTP-WallPanel-2', 'Wall Panel', 'Sub-frame', 2, NOW()),
('PTP-WallPanel-3', 'Wall Panel', 'Decor surface', 3, NOW()),
('PTP-WallPanel-4', 'Wall Panel', 'Fixing clips', 4, NOW()),

('PTP-PartitionWall-1', 'Partition Wall', 'Frame', 1, NOW()),
('PTP-PartitionWall-2', 'Partition Wall', 'Double panels', 2, NOW()),
('PTP-PartitionWall-3', 'Partition Wall', 'Core insulation', 3, NOW()),
('PTP-PartitionWall-4', 'Partition Wall', 'Top / bottom rails', 4, NOW()),

('PTP-VisualLarge-1', 'Visual Large', 'Main frame', 1, NOW()),
('PTP-VisualLarge-2', 'Visual Large', 'Printed visual', 2, NOW()),
('PTP-VisualLarge-3', 'Visual Large', 'Panels', 3, NOW()),
('PTP-VisualLarge-4', 'Visual Large', 'Lighting', 4, NOW()),
('PTP-VisualLarge-5', 'Visual Large', 'Logo holder', 5, NOW()),

('PTP-VisualSmall-1', 'Visual Small', 'Frame', 1, NOW()),
('PTP-VisualSmall-2', 'Visual Small', 'Visual print', 2, NOW()),
('PTP-VisualSmall-3', 'Visual Small', 'Panel', 3, NOW()),
('PTP-VisualSmall-4', 'Visual Small', 'Lighting', 4, NOW()),

('PTP-Flooring-1', 'Flooring', 'Base boards', 1, NOW()),
('PTP-Flooring-2', 'Flooring', 'Finish layer', 2, NOW()),
('PTP-Flooring-3', 'Flooring', 'Transition strips', 3, NOW()),
('PTP-Flooring-4', 'Flooring', 'Plinth', 4, NOW()),

('PTP-LightingFixture-1', 'Lighting Fixture', 'Frame', 1, NOW()),
('PTP-LightingFixture-2', 'Lighting Fixture', 'LED panel', 2, NOW()),
('PTP-LightingFixture-3', 'Lighting Fixture', 'Diffuser', 3, NOW()),
('PTP-LightingFixture-4', 'Lighting Fixture', 'Cable channel', 4, NOW()),

('PTP-DecorFrame-1', 'Decor Frame', 'Outer frame', 1, NOW()),
('PTP-DecorFrame-2', 'Decor Frame', 'Insert visual', 2, NOW()),
('PTP-DecorFrame-3', 'Decor Frame', 'Mounting brackets', 3, NOW());
